### ISSUE TITLE
[Bug Report]: Packaging error

### ISSUE THREAD

**Issue by tlerbao** [webdevnerdstuff/vue-code-block#42]
### Bug description

Error when packaging
<img width="1267" alt="CleanShot 2023-12-18 at 11 04 10@2x" src="https://github.com/webdevnerdstuff/vue-code-block/assets/20442232/a040ace8-f1c4-4843-b5fb-8a5dcf415656">

When I encapsulated this component for the second time, the IDE did not report any errors at all. It only reported errors during packaging.
<img width="1165" alt="CleanShot 2023-12-18 at 11 05 00@2x" src="https://github.com/webdevnerdstuff/vue-code-block/assets/20442232/a26e4239-c373-4587-a8fe-b081e771a9d8">

### Steps to reproduce

Error when packaging

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by webdevnerdstuff** [comment]
What version of the plugin are you using? (Also please use English if possible)

**Comment by tlerbao** [comment]
@webdevnerdstuff 

I'm sorry, I thought it was developed by Chinese developers. The version I'm using is 2.3.1. Thanks for the open source!

<img width="460" alt="CleanShot 2023-12-18 at 11 16 09@2x" src="https://github.com/webdevnerdstuff/vue-code-block/assets/20442232/ac18a984-37e5-4a6b-9fb7-8e5388b59666">

**Comment by webdevnerdstuff** [comment]
I added this repo to test but wasn't able to replicate the issue. Perhaps you can adjust it so that it's closer to your setup?

https://github.com/webdevnerdstuff/vcb-issue-32

**Comment by webdevnerdstuff** [comment]
Closing the issue due to inactivity
