### ISSUE TITLE
[Bug Report]: 

### ISSUE THREAD

**Issue by winneryong** [webdevnerdstuff/vue-code-block#58]
### Vue Code Block Version

2.3.3

### Vue Version

3

### Bug description

```
<VCodeBlock
    :code="code"
    highlightjs
    label="Hello World"
    lang="html"
    theme="neon-bunny"
  />
```
When the `code` value is updated to be empty, the displayed content does not update.

### Steps to reproduce

1. set `code` value ```<html><body>123</body></html>```
2. code viewer display ```<html><body>123</body></html>```
3. set `code` value to empty string ``
4. code viewer always display ```<html><body>123</body></html>```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by webdevnerdstuff** [comment]
This is how the code libraries work. To have the code update you would need to re-render the component. A quick and dirty method would be to give the code block element a key, and when the code changes, change the key.

ex.
```html
<VCodeBlock
  :key="blockKey"
  :code="code"
  :highlightjs="true"
  lang="js"
/>

<button @click="code = `const foo = 'bar';`; blockKey = 2;">Change Code</button>

<script setup>
  const code = ref(`const foo = 'foo';`);
  const blockKey = ref(1);
</script>
```
