### ISSUE TITLE
[Bug Report]: Copy to clipboard fails with no https

### ISSUE THREAD

**Issue by mirkovancolen** [webdevnerdstuff/vue-code-block#61]
### Vue Code Block Version

2.3.3

### Vue Version

3.5.15

### Bug description

When running in development for example and https is not enable, the copy block fails.  There are better ways in vue to do clipboard without breaking.

`import { copyText } from 'vue3-clipboard'`

### Steps to reproduce

run locally in dev non https

### Relevant log output

```shell
chunk-TF6X5W6F.js?v=991275c7:2329 Uncaught TypeError: Cannot read properties of undefined (reading 'writeText')
    at P (@wdns_vue-code-block.js?v=991275c7:1436:53)
    at callWithErrorHandling (chunk-TF6X5W6F.js?v=991275c7:2260:19)
    at callWithAsyncErrorHandling (chunk-TF6X5W6F.js?v=991275c7:2267:17)
    at HTMLDivElement.invoker (chunk-TF6X5W6F.js?v=991275c7:11155:5)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by webdevnerdstuff** [comment]
Would you please provide a more through example (or on StackBlitz) as to what you are doing exactly to cause this error? I don't use vue3-clipboard so I'm not familiar with it, but it also hasn't been updated in 4 years.

**Comment by mirkovancolen** [comment]
Hi, I'm sure you clipboard approach works fine in production with https, so any sample in a secured environment will work.  You use the browser mechanism **navigator.writeText**, but that fails in dev non https.  I'm not saying you need to use vue3-clipboard, it's a wrapper around https://github.com/zenorocha/clipboard.js which in its turn uses **document.execCommand** and adding a temp element to the DOM.  That seems to work fine.  It's BTW not because a repo hasn't been touched that it's end of life.  Sometimes something just works and doesn't need any fixing.

**Comment by mirkovancolen** [comment]
use this : 

```
async function copyToClipboard(textToCopy) {
    // Navigator clipboard api needs a secure context (https)
    if (navigator.clipboard && window.isSecureContext) {
        await navigator.clipboard.writeText(textToCopy);
    } else {
        // Use the 'out of viewport hidden text area' trick
        const textArea = document.createElement("textarea");
        textArea.value = textToCopy;
            
        // Move textarea out of the viewport so it's not visible
        textArea.style.position = "absolute";
        textArea.style.left = "-999999px";
            
        document.body.prepend(textArea);
        textArea.select();

        try {
            document.execCommand('copy');
        } catch (error) {
            console.error(error);
        } finally {
            textArea.remove();
        }
    }
}
```

you can then do

`await copyToClipboard(...)`

**Comment by webdevnerdstuff** [comment]
I'm still not sure I fully understand how to replicate this. My dev playground I use is http/localhost, not https and it always works. Without a fully working example I can use to replicate locally it's hard to problem solve.

Is it browser specific? Is the http you are using localhost, or an actual http site?

**Comment by mirkovancolen** [comment]
It's a browser thing.  Chrome simply does not allow access to the clipboard is not https / not localhost / or if not manually unblocked.  https://web.dev/articles/async-clipboard

**Comment by webdevnerdstuff** [comment]
I am using the Clipboard API currently.
https://github.com/webdevnerdstuff/vue-code-block/blob/main/src/plugin/VCodeBlock.vue#L366

The page you gave also shows it as being supported by Chrome.
https://web.dev/articles/async-clipboard#writetext

If you have a repo or example on something like StackBlitz you can give to me to replicate the issue I can check it out, but without it I'm going to have to close the issue as I still don't understand why it's not working for you, but is for me and others.

**Comment by mirkovancolen** [comment]
That's unfair.  I cannot show a non-secure context in StackBlitz, 
But fair enough as this will only happen in dev mode.

https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts/features_restricted_to_secure_contexts => this link shows all the browser api's that only work in secure context.

https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts => this explains when something is in secure context.

http is only allowed with localhost or 127.0.0.1 => all others require https.  In my case I spin-up a node-js-express app in dev mode (http port 8000) which I access from my dev jumphost.

When you spin up your "dev" with http://localhost => do me a favor and try to access it from another machine... clipboard will fail.

**Comment by webdevnerdstuff** [comment]
You're right—StackBlitz might not be the best option here. I can’t fix what I can’t replicate, so it would help if you set up a simple repo with a minimal site I can test. Please include detailed steps to replicate the issue, as everything works fine for me locally on http, https, and live sites.

When you mention accessing my localhost from another machine, do you mean opening it via the local network (using IP, ipconfig, etc.)? Or are you referring to tools like Mac's Screenshare or another Mac/Win app like TeamViewer?

This seems like a very specific use case, so the more details, code, and clear steps you can provide, the better I can help troubleshoot.

**Comment by mirkovancolen** [comment]
It's very simple : spin up the simplest webapp with the clipboard part, access it of http from "non-localhost" (for example http://172.16.0.1) and you'll see it doesn't work.  It's very specific for a dev setup and you don't need to change it for me, I'm just reaching you the solution which I know works, because I implemented it on my end.

**Comment by webdevnerdstuff** [comment]
I want to help you, but I need the proper resources to do so. Vague instructions are not helpful, especially when I’ve repeatedly asked for a repository or a clear example. Without a repository that includes detailed instructions and steps to reproduce the issue, I will not be looking into this further. Please provide what’s needed if you want me to proceed.
